version: "3.7"
services:
  backend:
    build:
      context: .
      target: runner
    networks:
      - grocery
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - "SPRING_PROFILES_ACTIVE=compose"
  mongo:
    image: "mongo"
    networks:
      - grocery
    ports:
      - "27017:27017"
    expose:
      - "27017"

networks:
  grocery:
    driver: bridge
